"""ECI AI Studio bridge behavior."""

from __future__ import annotations

import httpx

from app.insights import ai_studio
from app.insights.ai_studio import AIStudioAgentClient, answer_with_optional_ai_studio
from app.insights.nlq import NLQueryEngine
from app.services import metric_engine, seed_tenant

TENANT = "acme-mfg"


def _local_answer():
    seed_tenant(TENANT)
    return NLQueryEngine(metric_engine).answer(TENANT, "Why did margins drop last month?")


def test_ai_studio_bridge_returns_local_answer_when_unconfigured():
    local = _local_answer()
    out = answer_with_optional_ai_studio(
        tenant_id=TENANT,
        question=local.question,
        local_answer=local,
        industry="manufacturing",
        client=AIStudioAgentClient(),
    )

    assert out["source"] == "local"
    assert out["agent"]["status"] == "not_configured"
    assert out["answer"] == local.answer


def test_ai_studio_bridge_uses_agent_answer(monkeypatch):
    captured = {}

    class FakeClient:
        def __init__(self, timeout: float) -> None:
            self.timeout = timeout

        def __enter__(self) -> "FakeClient":
            return self

        def __exit__(self, *args: object) -> None:
            return None

        def post(self, url: str, json: dict, headers: dict) -> httpx.Response:
            captured["url"] = url
            captured["json"] = json
            captured["headers"] = headers
            request = httpx.Request("POST", url)
            return httpx.Response(
                200,
                json={
                    "answer": "AI Studio says supplier costs drove the margin drop.",
                    "explanation": "Generated by the configured agent.",
                },
                request=request,
            )

    monkeypatch.setattr(ai_studio.httpx, "Client", FakeClient)

    local = _local_answer()
    out = answer_with_optional_ai_studio(
        tenant_id=TENANT,
        question=local.question,
        local_answer=local,
        industry="manufacturing",
        client=AIStudioAgentClient(
            agent_url="https://ai-studio.example.test/agents/run",
            api_key="test-key",
            agent_id="margin-advisor",
        ),
    )

    assert out["source"] == "eci_ai_studio"
    assert out["answer"] == "AI Studio says supplier costs drove the margin drop."
    assert out["agent"]["agent_id"] == "margin-advisor"
    assert captured["headers"]["Authorization"] == "Bearer test-key"
    assert captured["json"]["tenant_id"] == TENANT
    assert captured["json"]["context"]["local_answer"]["resolved_query"]["metric"] == "gross_margin_pct"
